name: model
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  camera: ^0.11.1
  flutter_tts: ^4.2.2
  image: ^4.0.15
  path_provider: ^2.0.13
  flutter_application_1: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/first_models.tflite
    - assets/labels.txt
    - Images/letters.jpg
    - Images/words.jpg
    - Images/sents.jpg
    - Images/logo.png
    - Images/lettera.jpg
    - Images/letterb.jpg
    - Images/letterc.jpg
    - Images/letterd.jpg
    - Images/lettert.jpg
    - Images/letteru.jpg
    - Images/letterv.jpg
    - Images/letterw.jpg
    - Images/letterx.jpg
    - Images/lettery.jpg
    - Images/letterz.jpg
    - Images/goodbye.png
    - Images/yes.png
    - Images/no.png
    - Images/please.png
    - Images/sorry.png
    - Images/help.png
    - Images/excuse.webp
    - Images/thanku.png
    - Images/hello.png
    - Images/howru.png
    - Images/love.jpg
    - Images/meet.png
    - Images/name.webp
    - Images/seeyou.jpg
    - Images/logoo.jpg
